### ISSUE TITLE
Rename DateTime.Now constant

### ISSUE THREAD

**Issue by MAGNAT2645** [KillStr3aK/DateTime#1]
Compiler throws an error `insufficient memory` for `DateTime.Now`.
Example:
`DateTime.Now().ToString()`

`DateTime.Now` should be renamed (at least without a dot).
`#define DateTime_Now -1`

**Comment by KillStr3aK** [comment]
May I ask your compiler version?
It compiles for me with 1.11

**Comment by MAGNAT2645** [comment]
1.10.0.6504

So, there's a change in 1.11 which allows same name for constants and functions?

**Comment by MAGNAT2645** [comment]
There are also these errors:
```
DateTime.inc(113) : error 017: undefined symbol "February"
DateTime.inc(119) : error 139: could not find type "EMonth"
DateTime.inc(121) : error 139: could not find type "EMonth"
DateTime.inc(124) : error 139: could not find type "EDay"
DateTime.inc(126) : error 139: could not find type "EDay"
DateTime.inc(195) : error 139: could not find type "EMonth"
```

So `DateTime/EDay.inc` and `DateTime/EMonth.inc` should be included inside `DateTime.inc`

**Comment by KillStr3aK** [comment]
> 1.10.0.6504
> 
> So, there's a change in 1.11 which allows same name for constants and functions?

I've misunderstood the issue for the first time!

**Comment by KillStr3aK** [comment]
> There are also these errors:
> 
> ```
> DateTime.inc(113) : error 017: undefined symbol "February"
> DateTime.inc(119) : error 139: could not find type "EMonth"
> DateTime.inc(121) : error 139: could not find type "EMonth"
> DateTime.inc(124) : error 139: could not find type "EDay"
> DateTime.inc(126) : error 139: could not find type "EDay"
> DateTime.inc(195) : error 139: could not find type "EMonth"
> ```
> 
> So `DateTime/EDay.inc` and `DateTime/EMonth.inc` should be included inside `DateTime.inc`

Thanks!
I've made the changes.
